CREATE DATABASE TASK

CREATE TABLE Academies
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL UNIQUE

)

CREATE TABLE Groups
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL UNIQUE,
	AcademyId INT FOREIGN KEY(AcademyId) REFERENCES Academies(Id)
)

CREATE TABLE Students
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL ,
	Surname NVARCHAR(20) NOT NULL ,
	Age TINYINT NOT NULL,
	GroupId INT FOREIGN KEY(GroupId) REFERENCES Groups(Id),
	Adulthood BIT DEFAULT 0
)

CREATE TABLE DeletedStudents
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL ,
	Surname NVARCHAR(20) NOT NULL ,
	GroupId INT NOT NULL
)

CREATE TABLE DeletedGroups
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL UNIQUE,
	AcademyId INT NOT NULL
)


CREATE VIEW VW_GETALLACADEMIES
AS
SELECT * FROM Academies


CREATE VIEW VW_GETALLGROUPS
AS
SELECT * FROM Groups


CREATE VIEW VW_GETALLSTUDENTS
AS
SELECT * FROM Students

CREATE PROCEDURE USP_GETGROUPBYNAME @Name NVARCHAR(20)
AS
SELECT * FROM VW_GETALLGROUPS
WHERE Name=@Name


CREATE PROCEDURE USP_GETSTUDENTSBYAGEUPPER @Age INT
AS
SELECT * FROM VW_GETALLSTUDENTS
WHERE Age>=@Age


CREATE PROCEDURE USP_GETSTUDENTSBYAGELOWER @Age INT
AS
SELECT * FROM VW_GETALLSTUDENTS
WHERE Age<=@Age

CREATE TRIGGER TRGGR_DeliteGroups
ON Groups
AFTER DELETE
AS
INSERT INTO DeletedGroups (Name,AcademyId)
SELECT Name,AcademyId FROM deleted

CREATE TRIGGER TRGGR_DeliteStudents
ON Students
AFTER DELETE
AS
INSERT INTO DeletedStudents(Name,Surname,GroupId)
SELECT Name,Surname,GroupId FROM deleted

CREATE TRIGGER TRGGR_AGE18
ON Students
AFTER INSERT
AS 
INSERT INTO Students(Adulthood)
SELECT Adulthood = 1 FROM Students
WHERE Age>=18

CREATE TRIGGER TRGGR_AGE18UP
ON Students
AFTER UPDATE
AS 
INSERT INTO Students(Adulthood)
SELECT Adulthood=1 FROM Students
WHERE Age>=18

INSERT INTO Academies
VALUES
('AzTU'),
('BDU')

INSERT INTO Groups
VALUES
('AB101',1),
('AB102',1),
('BD101',2),
('BD102',2)

INSERT INTO Students(Name,Surname,Age,GroupId)
VALUES
('Maqa','Abdullayev',17,1),
('Ahmat','Zigmund',22,1),
('Danil','Bereberli',21,2),
('Anton','Chekov',17,2),
('Vitaliy','Anatolivich',18,3),
('Elcan','Ceferov',16,3),
('Donald','Tramp',32,4),
('Jastin','Babazade',27,4)



SELECT * FROM Students